In [1]:
import numpy as np

In [2]:
my_array = np.array([1, 2, 3, 4, 5])

In [3]:
my_array

array([1, 2, 3, 4, 5])

In [4]:
random_nums = np.random.randint(1, 100, size=5)
print(random_nums)

[10 74  1 17 67]


In [5]:
a = np.arange(15).reshape(3, 5)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])

In [14]:
b

array([6, 7, 8])

In [15]:
type(b)

numpy.ndarray

In [16]:
a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1, 2, 3, 4])  # RIGHT

In [ ]:
a

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [ ]:
b

In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [ ]:
c

In [ ]:
np.zeros((3, 4))

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

In [ ]:
np.empty((2, 3))

In [ ]:
np.arange(10, 30, 5)

In [ ]:
np.arange(0, 2, 0.3)  # it accepts float arguments

In [ ]:
from numpy import pi

In [17]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points

NameError: name 'pi' is not defined

In [19]:
x

NameError: name 'x' is not defined

In [20]:
f = np.sin(x)

NameError: name 'x' is not defined

In [21]:
a = np.arange(6)                    # 1d array

In [22]:
(a)

array([0, 1, 2, 3, 4, 5])

In [23]:
b = np.arange(12).reshape(4, 3)     # 2d array

In [24]:
(b)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array

In [26]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
(np.arange(10000))

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [28]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [29]:
a = np.array([20, 30, 40, 50])

In [30]:
a

array([20, 30, 40, 50])

In [31]:
b = np.arange(4)

In [32]:
b

array([0, 1, 2, 3])

In [33]:
c = a - b

In [34]:
c

array([20, 29, 38, 47])

In [35]:
b**2

array([0, 1, 4, 9])

In [36]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a < 35

array([ True,  True, False, False])

In [38]:
A = np.array([[1, 1],
              [0, 1]])

In [39]:
A

array([[1, 1],
       [0, 1]])

In [40]:
B = np.array([[2, 0],
              [3, 4]])

In [41]:
B

array([[2, 0],
       [3, 4]])

In [42]:
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [43]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [44]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [45]:
B = np.arange(3)

In [46]:
B

array([0, 1, 2])

In [47]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [48]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [49]:
C = np.array([2., -1., 4.])

In [50]:
C

array([ 2., -1.,  4.])

In [51]:
np.add(B, C)

array([2., 0., 6.])

In [52]:
rg = np.random.default_rng(1)  # create instance of default random number generator

In [53]:
rg

Generator(PCG64) at 0x230A3251FC0

In [54]:
a = np.ones((2, 3), dtype=int)

In [55]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
b = rg.random((2, 3))

In [57]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [58]:
a *= 3

In [59]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [60]:
b += a

In [61]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [62]:
a = b  # b is not automatically converted to integer type

In [63]:
a

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [64]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [65]:
a = np.arange(10)**3

In [66]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [67]:
a[2]

8

In [68]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [69]:
# equivalent to a[0:6:2] = 1000;

In [70]:
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000

In [71]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [72]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [73]:
for i in a:
    print(i**(1 / 3.))  #find cube root

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [74]:
def f(x, y):
    return 10 * x + y

In [75]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [76]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [77]:
b[2, 3]

23

In [78]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [79]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [80]:
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [81]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

In [82]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [83]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [84]:
c.shape

(2, 2, 3)

In [85]:
c[1, ...]  # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [86]:
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [87]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [88]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [89]:
a = np.floor(10 * rg.random((3, 4)))

In [90]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [91]:
a.shape

(3, 4)

In [92]:
a.ravel()  # returns the array, flattened

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [93]:
a.reshape(6, 2)  # returns the array with a modified shap

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [94]:
a.T  # returns the array, transposed

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [95]:
a.T.shape

(4, 3)

In [96]:
a.shape

(3, 4)

In [97]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [98]:
a.resize((2, 6))

In [99]:
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

In [100]:
a.reshape(3, -1)

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [101]:
import numpy as np

In [102]:
data1=[6, 4, 7, 7, 9, 2, 0, 3]

In [103]:
data1

[6, 4, 7, 7, 9, 2, 0, 3]

In [104]:
arr1 = np.array(data1)

In [105]:
arr1

array([6, 4, 7, 7, 9, 2, 0, 3])

In [106]:
arr1.dtype

dtype('int32')

In [107]:
print(arr1.shape)


(8,)


In [108]:
print(arr1.ndim)


1


In [109]:
data2=[[1, 2, 3, 4], [5, 6, 7, 8]]  #list of lists

In [110]:
arr2 = np.array(data2)


In [111]:
print(arr2.ndim)   #2

2


In [112]:
print(arr2.shape)  # (2,4)

(2, 4)


In [113]:
arr = np.arange(10)

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
arr[9]

9

In [116]:
arr[5:8] #[5 6 7]

array([5, 6, 7])

In [117]:
arr[9] = 12345


In [118]:
arr

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
       12345])

In [119]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)

In [120]:
bool_arr

array([ True,  True, False, False,  True, False,  True, False])

In [121]:
arr_1 = np.random.randn(3, 3)
arr_2 = np.random.randn(3, 3)

In [122]:
bool_arr = arr_1 < 0.5

In [123]:
bool_arr.dtype

dtype('bool')

In [124]:
bool_arr = arr_1 < arr_2

In [125]:
bool_arr.dtype

dtype('bool')